services:
  nginx-ras:
    image: "nginx:stable-alpine"
    ports:
      - "8000:90"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php-ras
      - mysql-ras
      - phpmyadmin
  php-ras:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
  mysql-ras:
    image: "mysql:latest"
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - 8080:80
    env_file:
      - env/phpmyadmin.env

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel